---
- name: app | clone git repo
  git: repo=$git_repo_address dest=$app_root
  tags: app

- name: app | distify app
  command: grunt dist chdir=$app_root

- name: app | install npm deps
  command: npm install chdir=$app_root/dist

- name: app | install bower deps
  command: bower install chdir=$app_root/dist

- name: "app | Install forever (to run Node.js app)."
  npm: name=forever global=yes state=latest

- name: "app | Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "app | Start example Node.js app."
  command: forever start $app_root/dist/server.js
  when: "forever_list.stdout.find('$app_root/dist/server.js') == -1"
