---
# File: setup.yml
# Part: nodejs
#
# Description: Installs nodejs from source
#
# Parameters - Must be definied in playbook:
#   - node_path = The nodejs path
#   - node_prefix = The prefix
#   - node_tarball = The tarball filename at nodejs.org
#   - node_version = The wanted version of node to be installed
- name: Node.js | Installing node from apt
  apt: name={{item}} state=installed
  with_items:
    - nodejs
    - npm
